spring:
  application:
    name: StoreAPI
  datasource:
    url: jdbc:postgresql://localhost:2345/postgres
    username: postgres
    password: local
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    database: postgresql
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: "UTC"

config:
  jwt:
    secretKey: "FURINA_SO_CUTE_UWU"
    issuer: "storeapi"
  payment:
    scb:
      apiUrl: "https://api-sandbox.partners.scb"
      clientId: ""
      clientSecret: ""
      merchantId: " "
    chillpay:
      apiUrl: "https://sandbox-appsrv2.chillpay.co"
      merchantId: ""
      apiKey: ""
      md5: ""
    slip:
      apiUrl: "https://suba.rdcw.co.th/v1/inquiry"
      clientId: ""
      clientSecret: ""
      postpaid: "0"
    tmn_voucher:
      mobile: "0881112222"
      rate: "2.3"
    promptpay:
      type: "MSISDN"
      value: "0882637623"
    bank:
      bankCode: "004"
      bankAccount: ""
      bankAccountName: "Mr. John doe"
  tracking:
    thailandpost:
      token: ""
      webhook: "THIS_IS_A_SECRET_TOKEN_PLEASE_NOT_SHARE_BTW_FURINA_CUTE"