package dev.mottolab.storeapi.provider.truemoney.voucher.response;

public enum TmnVoucherStatus {
    VOUCHER_OUT_OF_STOCK,
    VOUCHER_NOT_FOUND,
    VOUCHER_EXPIRED,
    TARGET_USER_NOT_FOUND,
    TRANSFER_MONEY_ERROR,
    TARGET_USER_REDEEMED,
    CANNOT_GET_OWN_VOUCHER,
    KYC_NOT_ALLOWED,
    TARGET_USER_STATUS_INACTIVE,
    OWNER_USER_STATUS_INACTIVE,
    RESERVED_TICKET,
    FETCH_VOUCHER_SUCCESS,
    FETCH_MOBILE_VOUCHER_SUCCESS,
    INTERNAL_ERROR,
    SUCCESS
}
